# Generated by Django 2.2.1 on 2019-05-25 14:46

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='body',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
