# Generated by Django 2.2 on 2019-05-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190425_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('body', models.TextField(db_index=True)),
                ('source', models.URLField(max_length=150, unique=True)),
            ],
        ),
    ]
