# Generated by Django 2.2.1 on 2019-05-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='post_slug',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='post_title',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='slug',
            new_name='tag_slug',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='tag_title',
        ),
    ]
